import { Migration } from "@mikro-orm/migrations";

const INITIAL_FISHES = [
    {
        fish_id: 1,
        name: "odiosis piscis",
        image: "https://i.imgur.com/XO1TV1j.png",
        rarity: 1.9,
        min_weight: 100,
        max_weight: 300,
        points_per_gramm: 2,
        reel_time_factor: 1,
    },
    {
        fish_id: 2,
        name: "minima pulchritudo",
        image: "https://i.imgur.com/U4zWofT.png",
        rarity: 1.9,
        min_weight: 50,
        max_weight: 120,
        points_per_gramm: 2,
        reel_time_factor: 1,
    },
    {
        fish_id: 3,
        name: "aurantium dulcis",
        image: "https://i.imgur.com/l1bxUm1.png",
        rarity: 1.8,
        min_weight: 100,
        max_weight: 300,
        points_per_gramm: 2,
        reel_time_factor: 1,
    },
    {
        fish_id: 4,
        name: "minilodon",
        image: "https://i.imgur.com/zf3S6LI.png",
        rarity: 1.5,
        min_weight: 1000,
        max_weight: 1500,
        points_per_gramm: 2,
        reel_time_factor: 0.5,
    },
    {
        fish_id: 5,
        name: "minilodon (shiny)",
        image: "https://i.imgur.com/uO8y6l9.png",
        rarity: 1.4,
        min_weight: 1000,
        max_weight: 1500,
        points_per_gramm: 5,
        reel_time_factor: 0.4,
    },
    {
        fish_id: 6,
        name: "lacus zucchini",
        image: "https://i.imgur.com/9UWTFzK.png",
        rarity: 1.7,
        min_weight: 100,
        max_weight: 200,
        points_per_gramm: 2,
        reel_time_factor: 1,
    },
    {
        fish_id: 7,
        name: "limoque obvoluto",
        image: "https://i.imgur.com/7bu5dfc.png",
        rarity: 1.7,
        min_weight: 100,
        max_weight: 200,
        points_per_gramm: 2,
        reel_time_factor: 1,
    },
    {
        fish_id: 8,
        name: "smugtopus",
        image: "https://i.imgur.com/0uxtQk2.png",
        rarity: 1.6,
        min_weight: 100,
        max_weight: 200,
        points_per_gramm: 3,
        reel_time_factor: 0.8,
    },
    {
        fish_id: 9,
        name: "diu flexilis",
        image: "https://i.imgur.com/N55Fxlh.png",
        rarity: 1.6,
        min_weight: 100,
        max_weight: 200,
        points_per_gramm: 2,
        reel_time_factor: 1,
    },
    {
        fish_id: 10,
        name: "musa acumiwater",
        image: "https://i.imgur.com/gxirbcL.png",
        rarity: 1.9,
        min_weight: 100,
        max_weight: 200,
        points_per_gramm: 2,
        reel_time_factor: 1,
    },
    {
        fish_id: 11,
        name: "ictus ictus ictus",
        image: "https://i.imgur.com/D3wQxp6.png",
        rarity: 1.7,
        min_weight: 100,
        max_weight: 200,
        points_per_gramm: 2,
        reel_time_factor: 1,
    },
    {
        fish_id: 12,
        name: "deformis faciem tuam",
        image: "https://i.imgur.com/izjh5Tn.png",
        rarity: 1.7,
        min_weight: 100,
        max_weight: 200,
        points_per_gramm: 3,
        reel_time_factor: 1,
    },
    {
        fish_id: 13,
        name: "Adidas(TM)",
        image: "https://i.imgur.com/zNg8iz7.png",
        rarity: 1.7,
        min_weight: 70,
        max_weight: 130,
        points_per_gramm: 1,
        reel_time_factor: 2.5,
    },
    {
        fish_id: 14,
        name: "puer magnus",
        image: "https://i.imgur.com/C4SwLWh.png",
        rarity: 1.6,
        min_weight: 200,
        max_weight: 400,
        points_per_gramm: 2,
        reel_time_factor: 1,
    },
    {
        fish_id: 15,
        name: "mini minilodon",
        image: "https://i.imgur.com/QzqHxTk.png",
        rarity: 1.5,
        min_weight: 300,
        max_weight: 360,
        points_per_gramm: 2,
        reel_time_factor: 0.9,
    },
    {
        fish_id: 16,
        name: "Can of Tuna",
        image: "https://i.imgur.com/SUHF7Sv.png",
        rarity: 1.7,
        min_weight: 20,
        max_weight: 40,
        points_per_gramm: 1,
        reel_time_factor: 2.5,
    },
];

export class Migration1 extends Migration {
    async up(): Promise<void> {
        const fishesInDb = (await this.ctx!.from("fish").count({ total: "fish_id" })) as { total: number }[];
        if (fishesInDb[0].total == 0) await this.ctx!.batchInsert("fish", INITIAL_FISHES);
    }
}
