# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: CI

on: [ push, pull_request ]
jobs:
  pre_job:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - name: Skip Duplicate Actions
        id: skip_check
        uses: fkirc/skip-duplicate-actions@v3.4.0
        with:
          github_token: ${{ github.token }}
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'
          concurrent_skipping: same_content
  setup:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [ 14.x ] #15.x not yet supported
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v2.1.5
        env:
          cache-name: cache-${{ matrix.node-version }}-node-modules
        with:
          path: ./node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}-${{ hashFiles('**/package-lock.json') }}

      - name: "Install"
        run: npm install
        env:
          CI: true

      - name: "Build"
        run: npm run build
        env:
          CI: true

      - name: "Test"
        run: npm run test
        env:
          CI: true

      - name: "Lint"
        run: npm run lint
        env:
          CI: true
