# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: CI

on: [ push, pull_request, workflow_dispatch ]
jobs:
  pre_job:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - name: Skip Duplicate Actions
        id: skip_check
        uses: fkirc/skip-duplicate-actions@v5.3.1
        with:
          github_token: ${{ github.token }}
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'
          concurrent_skipping: same_content
  ci:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: "Install"
        run: npm ci
        env:
          CI: true

      - name: "Build"
        run: npm run build
        env:
          CI: true

      - name: "Test"
        run: npm run test
        env:
          CI: true

      - name: "Lint"
        run: npm run lint
        env:
          CI: true

      - name: "Unused Dependencies"
        run: npm run dep-check-unused
        env:
          CI: true
